python activation.py --method xgradcam --image ./selected/case13axial.jpg --case 13 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case13coronal.jpg --case 13 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case13sagittal.jpg --case 13 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case16axial.jpg --case 16 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case16coronal.jpg --case 16 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case16sagittal.jpg --case 16 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case30axial.jpg --case 30 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case30coronal.jpg --case 30 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case30sagittal.jpg --case 30 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case33axial.jpg --case 33 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case33coronal.jpg --case 33 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case33sagittal.jpg --case 33 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case61axial.jpg --case 61 -plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case61coronal.jpg --case 61 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case61sagittal.jpg --case 61 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case76axial.jpg --case 76 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case76coronal.jpg --case 76 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case76sagittal.jpg --case 76 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case77axial.jpg --case 77 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case77coronal.jpg --case 77 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case77sagittal.jpg --case 77 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case83axial.jpg --case 83 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case83coronal.jpg --case 83 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case83sagittal.jpg --case 83 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case86axial.jpg --case 86 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case86coronal.jpg --case 86 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case86sagittal.jpg --case 86 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case94axial.jpg --case 94 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case94coronal.jpg --case 94 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case94sagittal.jpg --case 94 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case97axial.jpg --case 97 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case97coronal.jpg --case 97 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case97sagittal.jpg --case 97 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case99axial.jpg --case 99 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case99coronal.jpg --case 99 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case99sagittal.jpg --case 99 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case100axial.jpg --case 100 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case100coronal.jpg --case 100 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case100sagittal.jpg --case 100 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case101axial.jpg --case 101 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case101coronal.jpg --case 101 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case101sagittal.jpg --case 101 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case107axial.jpg --case 107 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case107coronal.jpg --case 107 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case107sagittal.jpg --case 107 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case115axial.jpg --case 115 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case115coronal.jpg --case 115 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case115sagittal.jpg --case 115 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case122axial.jpg --case 122 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case122coronal.jpg --case 122 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case122sagittal.jpg --case 122 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case123axial.jpg --case 123 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case123coronal.jpg --case 123 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case123sagittal.jpg --case 123 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case137axial.jpg --case 137 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case137coronal.jpg --case 137 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case137sagittal.jpg --case 137 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case146axial.jpg --case 146 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case146coronal.jpg --case 146 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case146sagittal.jpg --case 146 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case150axial.jpg --case 150 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case150coronal.jpg --case 150 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case150sagittal.jpg --case 150 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case158axial.jpg --case 158 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case158coronal.jpg --case 158 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case158sagittal.jpg --case 158 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case169axial.jpg --case 169 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case169coronal.jpg --case 169 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case169sagittal.jpg --case 169 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case174axial.jpg --case 174 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case174coronal.jpg --case 174 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case174sagittal.jpg --case 174 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case176axial.jpg --case 176 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case176coronal.jpg --case 176 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case176sagittal.jpg --case 176 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case179axial.jpg --case 179 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case179coronal.jpg --case 179 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case179sagittal.jpg --case 179 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case182axial.jpg --case 182 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case182coronal.jpg --case 182 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case182sagittal.jpg --case 182 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case188axial.jpg --case 188 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case188coronal.jpg --case 188 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case188sagittal.jpg --case 188 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case190axial.jpg --case 190 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case190coronal.jpg --case 190 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case190sagittal.jpg --case 190 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case193axial.jpg --case 193 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case193coronal.jpg --case 193 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case193sagittal.jpg --case 193 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case197axial.jpg --case 197 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case197coronal.jpg --case 197 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case197sagittal.jpg --case 197 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case199axial.jpg --case 199 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case199coronal.jpg --case 199 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case199sagittal.jpg --case 199 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case205axial.jpg --case 205 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case205coronal.jpg --case 205 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case205sagittal.jpg --case 205 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case207axial.jpg --case 207 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case207coronal.jpg --case 207 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case207sagittal.jpg --case 207 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case208axial.jpg --case 208 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case208coronal.jpg --case 208 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case208sagittal.jpg --case 208 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case209axial.jpg --case 209 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case209coronal.jpg --case 209 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case209sagittal.jpg --case 209 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case214axial.jpg --case 214 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case214coronal.jpg --case 214 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case214sagittal.jpg --case 214 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case219axial.jpg --case 219 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case219coronal.jpg --case 219 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case219sagittal.jpg --case 219 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case227axial.jpg --case 227 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case227coronal.jpg --case 227 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case227sagittal.jpg --case 227 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case230axial.jpg --case 230 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case230coronal.jpg --case 230 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case230sagittal.jpg --case 230 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case231axial.jpg --case 231 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case231coronal.jpg --case 231 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case231sagittal.jpg --case 231 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case236axial.jpg --case 236 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case236coronal.jpg --case 236 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case236sagittal.jpg --case 236 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case238axial.jpg --case 238 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case238coronal.jpg --case 238 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case238sagittal.jpg --case 238 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case241axial.jpg --case 241 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case241coronal.jpg --case 241 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case241sagittal.jpg --case 241 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case244axial.jpg --case 244 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case244coronal.jpg --case 244 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case244sagittal.jpg --case 244 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case245axial.jpg --case 245 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case245coronal.jpg --case 245 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case245sagittal.jpg --case 245 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case258axial.jpg --case 258 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case258coronal.jpg --case 258 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case258sagittal.jpg --case 258 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case259axial.jpg --case 259 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case259coronal.jpg --case 259 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case259sagittal.jpg --case 259 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case261axial.jpg --case 261 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case261coronal.jpg --case 261 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case261sagittal.jpg --case 261 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case265axial.jpg --case 265 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case265coronal.jpg --case 265 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case265sagittal.jpg --case 265 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case266axial.jpg --case 266 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case266coronal.jpg --case 266 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case266sagittal.jpg --case 266 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case271axial.jpg --case 271 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case271coronal.jpg --case 271 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case271sagittal.jpg --case 271 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case272axial.jpg --case 272 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case272coronal.jpg --case 272 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case272sagittal.jpg --case 272 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case275axial.jpg --case 275 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case275coronal.jpg --case 275 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case275sagittal.jpg --case 275 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case276axial.jpg --case 276 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case276coronal.jpg --case 276 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case276sagittal.jpg --case 276 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case277axial.jpg --case 277 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case277coronal.jpg --case 277 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case277sagittal.jpg --case 277 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case279axial.jpg --case 279 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case279coronal.jpg --case 279 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case279sagittal.jpg --case 279 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case280axial.jpg --case 280 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case280coronal.jpg --case 280 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case280sagittal.jpg --case 280 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case281axial.jpg --case 281 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case281coronal.jpg --case 281 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case281sagittal.jpg --case 281 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case282axial.jpg --case 282 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case282coronal.jpg --case 282 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case282sagittal.jpg --case 282 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case283axial.jpg --case 283 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case283coronal.jpg --case 283 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case283sagittal.jpg --case 283 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case284axial.jpg --case 284 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case284coronal.jpg --case 284 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case284sagittal.jpg --case 284 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case285axial.jpg --case 285 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case285coronal.jpg --case 285 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case285sagittal.jpg --case 285 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case286axial.jpg --case 286 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case286coronal.jpg --case 286 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case286sagittal.jpg --case 286 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case288axial.jpg --case 288 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case288coronal.jpg --case 288 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case288sagittal.jpg --case 288 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case289axial.jpg --case 289 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case289coronal.jpg --case 289 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case289sagittal.jpg --case 289 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case291axial.jpg --case 291 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case291coronal.jpg --case 291 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case291sagittal.jpg --case 291 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case293axial.jpg --case 293 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case293coronal.jpg --case 293 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case293sagittal.jpg --case 293 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case294axial.jpg --case 294 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case294coronal.jpg --case 294 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case294sagittal.jpg --case 294 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case295axial.jpg --case 295 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case295coronal.jpg --case 295 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case295sagittal.jpg --case 295 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case296axial.jpg --case 296 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case296coronal.jpg --case 296 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case296sagittal.jpg --case 296 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case297axial.jpg --case 297 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case297coronal.jpg --case 297 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case297sagittal.jpg --case 297 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case298axial.jpg --case 298 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case298coronal.jpg --case 298 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case298sagittal.jpg --case 298 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case299axial.jpg --case 299 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case299coronal.jpg --case 299 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case299sagittal.jpg --case 299 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case300axial.jpg --case 300 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case300coronal.jpg --case 300 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case300sagittal.jpg --case 300 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case303axial.jpg --case 303 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case303coronal.jpg --case 303 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case303sagittal.jpg --case 303 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case309axial.jpg --case 309 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case309coronal.jpg --case 309 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case309sagittal.jpg --case 309 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case314axial.jpg --case 314 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case314coronal.jpg --case 314 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case314sagittal.jpg --case 314 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case323axial.jpg --case 323 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case323coronal.jpg --case 323 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case323sagittal.jpg --case 323 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case324axial.jpg --case 324 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case324coronal.jpg --case 324 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case324sagittal.jpg --case 324 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case325axial.jpg --case 325 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case325coronal.jpg --case 325 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case325sagittal.jpg --case 325 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case326axial.jpg --case 326 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case326coronal.jpg --case 326 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case326sagittal.jpg --case 326 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case329axial.jpg --case 329 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case329coronal.jpg --case 329 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case329sagittal.jpg --case 329 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case339axial.jpg --case 339 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case339coronal.jpg --case 339 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case339sagittal.jpg --case 339 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case370axial.jpg --case 370 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case370coronal.jpg --case 370 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case370sagittal.jpg --case 370 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case381axial.jpg --case 381 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case381coronal.jpg --case 381 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case381sagittal.jpg --case 381 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case394axial.jpg --case 394 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case394coronal.jpg --case 394 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case394sagittal.jpg --case 394 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case399axial.jpg --case 399 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case399coronal.jpg --case 399 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case399sagittal.jpg --case 399 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case404axial.jpg --case 404 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case404coronal.jpg --case 404 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case404sagittal.jpg --case 404 --plane sagittal --metric 3
python activation.py --method xgradcam --image ./selected/case405axial.jpg --case 405 --plane axial --metric 3
python activation.py --method xgradcam --image ./selected/case405coronal.jpg --case 405 --plane coronal --metric 3
python activation.py --method xgradcam --image ./selected/case405sagittal.jpg --case 405 --plane sagittal --metric 3